package com.pfagestionnote.model;

// Generated 11 avr. 2016 15:53:53 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Absence generated by hbm2java
 */ 
@Entity
@Table(name = "absence", catalog = "gestion_scolarite")
public class Absence implements java.io.Serializable {

	private int id;
	private Double nbHeures;
	private Set<EtudiantHasMatiere> etudiantHasMatieres = new HashSet<EtudiantHasMatiere>(
			0);

	public Absence() {
	}

	public Absence(int id) {
		this.id = id;
	}

	public Absence(int id, Double nbHeures,
			Set<EtudiantHasMatiere> etudiantHasMatieres) {
		this.id = id;
		this.nbHeures = nbHeures;
		this.etudiantHasMatieres = etudiantHasMatieres;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nbHeures", precision = 22, scale = 0)
	public Double getNbHeures() {
		return this.nbHeures;
	}

	public void setNbHeures(Double nbHeures) {
		this.nbHeures = nbHeures;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "absence")
	public Set<EtudiantHasMatiere> getEtudiantHasMatieres() {
		return this.etudiantHasMatieres;
	}

	public void setEtudiantHasMatieres(
			Set<EtudiantHasMatiere> etudiantHasMatieres) {
		this.etudiantHasMatieres = etudiantHasMatieres;
	}

}
