package com.pfagestionnote.model;

// Generated 11 avr. 2016 15:53:53 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EtudiantHasMatiereId generated by hbm2java
 */
@Embeddable
public class EtudiantHasMatiereId implements java.io.Serializable {

	private int etudiantId;
	private int matiereId;

	public EtudiantHasMatiereId() {
	}

	public EtudiantHasMatiereId(int etudiantId, int matiereId) {
		this.etudiantId = etudiantId;
		this.matiereId = matiereId;
	}

	@Column(name = "Etudiant_id", nullable = false)
	public int getEtudiantId() {
		return this.etudiantId;
	}

	public void setEtudiantId(int etudiantId) {
		this.etudiantId = etudiantId;
	}

	@Column(name = "Matiere_id", nullable = false)
	public int getMatiereId() {
		return this.matiereId;
	}

	public void setMatiereId(int matiereId) {
		this.matiereId = matiereId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EtudiantHasMatiereId))
			return false;
		EtudiantHasMatiereId castOther = (EtudiantHasMatiereId) other;

		return (this.getEtudiantId() == castOther.getEtudiantId())
				&& (this.getMatiereId() == castOther.getMatiereId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEtudiantId();
		result = 37 * result + this.getMatiereId();
		return result;
	}

}
