package com.pfagestionnote.model;

// Generated 11 avr. 2016 15:53:53 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EtudiantHasMatiere generated by hbm2java
 */
@Entity
@Table(name = "etudiant_has_matiere", catalog = "gestion_scolarite")
public class EtudiantHasMatiere implements java.io.Serializable {

	private EtudiantHasMatiereId id;
	private Note note;
	private Matiere matiere;
	private Absence absence;
	private Etudiant etudiant;

	public EtudiantHasMatiere() {
	}

	public EtudiantHasMatiere(EtudiantHasMatiereId id, Note note,
			Matiere matiere, Absence absence, Etudiant etudiant) {
		this.id = id;
		this.note = note;
		this.matiere = matiere;
		this.absence = absence;
		this.etudiant = etudiant;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "etudiantId", column = @Column(name = "Etudiant_id", nullable = false)),
			@AttributeOverride(name = "matiereId", column = @Column(name = "Matiere_id", nullable = false)) })
	public EtudiantHasMatiereId getId() {
		return this.id;
	}

	public void setId(EtudiantHasMatiereId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Note_id", nullable = false)
	public Note getNote() {
		return this.note;
	}

	public void setNote(Note note) {
		this.note = note;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Matiere_id", nullable = false, insertable = false, updatable = false)
	public Matiere getMatiere() {
		return this.matiere;
	}

	public void setMatiere(Matiere matiere) {
		this.matiere = matiere;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Absence_id", nullable = false)
	public Absence getAbsence() {
		return this.absence;
	}

	public void setAbsence(Absence absence) {
		this.absence = absence;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Etudiant_id", nullable = false, insertable = false, updatable = false)
	public Etudiant getEtudiant() {
		return this.etudiant;
	}

	public void setEtudiant(Etudiant etudiant) {
		this.etudiant = etudiant;
	}

}
