package com.pfagestionnote.model;

// Generated 11 avr. 2016 15:53:53 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Note generated by hbm2java
 */
@Entity
@Table(name = "note", catalog = "gestion_scolarite")
public class Note implements java.io.Serializable {

	private int id;
	private Double examan;
	private Double ds;
	private Double autreNote;
	private Double moyenne;
	private Set<EtudiantHasMatiere> etudiantHasMatieres = new HashSet<EtudiantHasMatiere>(
			0);

	public Note() {
	}

	public Note(int id) {
		this.id = id;
	}

	public Note(int id, Double examan, Double ds, Double autreNote,
			Double moyenne, Set<EtudiantHasMatiere> etudiantHasMatieres) {
		this.id = id;
		this.examan = examan;
		this.ds = ds;
		this.autreNote = autreNote;
		this.moyenne = moyenne;
		this.etudiantHasMatieres = etudiantHasMatieres;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "examan", precision = 22, scale = 0)
	public Double getExaman() {
		return this.examan;
	}

	public void setExaman(Double examan) {
		this.examan = examan;
	}

	@Column(name = "ds", precision = 22, scale = 0)
	public Double getDs() {
		return this.ds;
	}

	public void setDs(Double ds) {
		this.ds = ds;
	}

	@Column(name = "autreNote", precision = 22, scale = 0)
	public Double getAutreNote() {
		return this.autreNote;
	}

	public void setAutreNote(Double autreNote) {
		this.autreNote = autreNote;
	}

	@Column(name = "moyenne", precision = 22, scale = 0)
	public Double getMoyenne() {
		return this.moyenne;
	}

	public void setMoyenne(Double moyenne) {
		this.moyenne = moyenne;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "note")
	public Set<EtudiantHasMatiere> getEtudiantHasMatieres() {
		return this.etudiantHasMatieres;
	}

	public void setEtudiantHasMatieres(
			Set<EtudiantHasMatiere> etudiantHasMatieres) {
		this.etudiantHasMatieres = etudiantHasMatieres;
	}

}
