package com.pfagestionnote.model;

// Generated 11 avr. 2016 15:53:53 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ReleveNote generated by hbm2java
 */
@Entity
@Table(name = "releve_note", catalog = "gestion_scolarite")
public class ReleveNote implements java.io.Serializable {

	private int id;
	private Etudiant etudiant;
	private Date annee;

	public ReleveNote() {
	}

	public ReleveNote(int id) {
		this.id = id;
	}

	public ReleveNote(int id, Etudiant etudiant, Date annee) {
		this.id = id;
		this.etudiant = etudiant;
		this.annee = annee;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Etudiant_id")
	public Etudiant getEtudiant() {
		return this.etudiant;
	}

	public void setEtudiant(Etudiant etudiant) {
		this.etudiant = etudiant;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "annee", length = 0)
	public Date getAnnee() {
		return this.annee;
	}

	public void setAnnee(Date annee) {
		this.annee = annee;
	}

}
