package com.pfagestionnote.model;

// Generated 11 avr. 2016 15:53:53 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Section generated by hbm2java
 */
@Entity
@Table(name = "section", catalog = "gestion_scolarite")
public class Section implements java.io.Serializable {

	private int id;
	private PlanEtude planEtude;
	private Departement departement;
	private String nom;
	private Set<Module> modules = new HashSet<Module>(0);
	private Set<Groupe> groupes = new HashSet<Groupe>(0);

	public Section() {
	}

	public Section(int id) {
		this.id = id;
	}

	public Section(int id, PlanEtude planEtude, Departement departement,
			String nom, Set<Module> modules, Set<Groupe> groupes) {
		this.id = id;
		this.planEtude = planEtude;
		this.departement = departement;
		this.nom = nom;
		this.modules = modules;
		this.groupes = groupes;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Plan_Etude_id")
	public PlanEtude getPlanEtude() {
		return this.planEtude;
	}

	public void setPlanEtude(PlanEtude planEtude) {
		this.planEtude = planEtude;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Departement_id")
	public Departement getDepartement() {
		return this.departement;
	}

	public void setDepartement(Departement departement) {
		this.departement = departement;
	}

	@Column(name = "nom", length = 45)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "section")
	public Set<Module> getModules() {
		return this.modules;
	}

	public void setModules(Set<Module> modules) {
		this.modules = modules;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "section")
	public Set<Groupe> getGroupes() {
		return this.groupes;
	}

	public void setGroupes(Set<Groupe> groupes) {
		this.groupes = groupes;
	}

}
